name: rsync to bsfr server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          # extended: true

      - name: Build
        run: hugo --minify
        
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BSFR_SSH }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Add known hosts
        run: ssh-keyscan -H 51.159.139.203 >> ~/.ssh/known_hosts
        
      - name: Deploy
        run: |
          rsync -vrhp -e "ssh -p 22"  --exclude ".*" --delete-after \
          --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
          /public/ b@51.159.139.203:/var/www/basilesimon.fr
